In [1]:
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.metrics import calinski_harabaz_score

from sklearn.ensemble import BaggingRegressor, RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import ExtraTreesRegressor, AdaBoostRegressor, GradientBoostingRegressor

from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV, cross_val_score
from sklearn.metrics import accuracy_score, mean_squared_error, mean_squared_log_error, make_scorer

pd.set_option('display.max_columns', None)

In [2]:
# Import dataset
df = pd.read_csv("train.csv")

In [3]:
# Make a pipeline to prepare data 
from sklearn.base import BaseEstimator, TransformerMixin

class FillNanValues(BaseEstimator, TransformerMixin):
    """
    Gets a DataFrame describing houses and fill the NaNs with meaningful replacements
    """
    def __init__(self): pass
    def fit(self, X, y=None):
        self.LotFrontageMedian = X.LotFrontage.median()
        self.MasVnrAreaMedian = X.MasVnrArea.median()
        return self
    def transform(self, X):
        X.LotFrontage.fillna(self.LotFrontageMedian, inplace=True)
        X.MasVnrArea.fillna(self.MasVnrAreaMedian, inplace=True)
        X.MiscFeature.fillna("NoShed", inplace=True)
        X.Fence.fillna('NoFence', inplace=True)
        X.BsmtQual.fillna("NoBasement", inplace=True)
        X.BsmtCond.fillna("NoBasement", inplace=True)
        X.BsmtExposure.fillna("NoBasement", inplace=True)
        X.BsmtFinType1.fillna("NoBasement", inplace=True)
        X.BsmtFinType2.fillna("NoBasement", inplace=True)
        X.BsmtFinType2.fillna("NoBasement", inplace=True)
        X.MasVnrType.fillna("None", inplace=True)
        X.Electrical.fillna("SBrkr", inplace=True)
        X.FireplaceQu.fillna('NoFP', inplace=True)
        X.GarageType.fillna('Attchd', inplace=True)
        X.GarageFinish.fillna('Unf', inplace=True)
        X.GarageQual.fillna('TA', inplace=True)
        X.GarageCond.fillna('TA', inplace=True)
        X.PoolQC.fillna("NoPool", inplace=True)
        return X

class RemoveColumns(BaseEstimator, TransformerMixin):
    """
    Get a DataFrame describing houses and removes irrelevant, repetative, or corrupt data
    Decisions based on EDA found in ML_Final_EDA.ipynb
    """
    def __init__(self): pass
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        return X.drop(
        ['GarageArea', 'BsmtHalfBath', 'MiscVal', 'MoSold',
        'YrSold', 'BsmtFinSF2', 'LowQualFinSF', '3SsnPorch', 
        'Utilities', 'Exterior2nd', 'Alley', 'Id'],
        axis = 1)

class AlterAttributes(BaseEstimator, TransformerMixin):
    """
    Get a DataFrame describing houses and alter some attributes 
    Decisions based on EDA found in ML_Final_EDA.ipynb
    """
    def __init__(self): pass
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        #Combine GarageCars == 3 and GarageCars == 4
        X.GarageCars = X.GarageCars.map(lambda x: 3 if (x == 4) else x)

        #Fill Nans in GarageYrBlt with median year
        X.GarageYrBlt = X.GarageYrBlt.fillna(X.GarageYrBlt.median())

        #Combine KitchenAbvGr 1 and 0 AND 2 and 3 such that it is binary
        X.KitchenAbvGr = X.KitchenAbvGr.map(lambda x: 0 if (x == 1) else x)
        X.KitchenAbvGr = X.KitchenAbvGr.map(lambda x: 1 if (x == 2 or x == 3) else x)

        #Make Pool Area binary (x>0 or x==0)--> 1 if they have pool else 0
        X.PoolArea = X.PoolArea.map(lambda x: 1 if (x>0) else x)
        return X

class GetDummies(BaseEstimator, TransformerMixin):
    """
    Get a DataFrame describing houses and convert all categorical attributes to one-hot encoded columns
    """
    def __init__(self): pass
    def fit(self, X, y=None):
        self.PriorData = pd.get_dummies(pd.DataFrame(X))
        self.columns = self.PriorData.columns
        return self
    def transform(self, X):
        temp = pd.get_dummies(X)
        for col in self.columns:
            if col not in temp.columns:
                temp_ar = np.zeros(temp.shape[0])
                for i in range(len(temp_ar)):
                    temp_ar[i]=self.PriorData[col].median()
                temp[col] = temp_ar
                
        for i,j in zip(temp.isnull().sum(), temp.columns):
            if i>0:
                temp[j].fillna(temp[j].median(), inplace=True)
        return pd.get_dummies(temp)

class ScaleData(BaseEstimator, TransformerMixin):
    """
    Get a DataFrame, center & scale it using the mean and standard devision 
    """
    def __init__(self): pass
    def fit(self, X, y=None):
        self.PriorData = X
        return self
    def transform(self, X):
        return (X-self.PriorData.mean())/self.PriorData.std()    

class GetDataFrame(BaseEstimator, TransformerMixin):
    """
    Get any data object and convert it to a Pandas DataFrame
    """
    def __init__(self): pass
    def fit(self, X, y=None):
        self.columns = pd.DataFrame(X).columns
        return self
    def transform(self, X):
        return pd.DataFrame(X, columns=self.columns).fillna(0)

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

Prep = Pipeline([
    ('fillnanvalues', FillNanValues()),
    ('removecolumns', RemoveColumns()),
    ('alterattributes', AlterAttributes()),
    ('getdummies', GetDummies()),
    ('scaledata', ScaleData()),
    ('getdataframe', GetDataFrame())
])

In [4]:
# Test pipeline
Prep.fit_transform(df).head(5)

MSSubClass  LotFrontage   LotArea  OverallQual  OverallCond  YearBuilt  \
0    0.073350    -0.220799 -0.207071     0.651256    -0.517023   1.050634   
1   -0.872264     0.460162 -0.091855    -0.071812     2.178881   0.156680   
2    0.073350    -0.084607  0.073455     0.651256    -0.517023   0.984415   
3    0.309753    -0.447787 -0.096864     0.651256    -0.517023  -1.862993   
4    0.073350     0.641752  0.375020     1.374324    -0.517023   0.951306   

   YearRemodAdd  MasVnrArea  BsmtFinSF1  BsmtUnfSF  TotalBsmtSF  1stFlrSF  \
0      0.878367    0.513928    0.575228  -0.944267    -0.459145 -0.793162   
1     -0.429430   -0.570555    1.171591  -0.641008     0.466305  0.257052   
2      0.829930    0.325803    0.092875  -0.301540    -0.313261 -0.627611   
3     -0.720051   -0.570555   -0.499103  -0.061648    -0.687089 -0.521555   
4      0.733056    1.366021    0.463410  -0.174805     0.199611 -0.045596   

   2ndFlrSF  GrLivArea  BsmtFullBath  FullBath  HalfBath  BedroomAbvGr  \
0  1.161454   0.370207      1.107431  0.789470  1.227165      0.163723   
1 -0.794891  -0.482347     -0.819684  0.789470 -0.761360      0.163723   
2  1.188943   0.514836      1.107431  0.789470  1.227165      0.163723   
3  0.936955   0.383528      1.107431 -1.025689 -0.761360      0.163723   
4  1.617323   1.298881      1.107431  0.789470  1.227165      1.389547   

   KitchenAbvGr  TotRmsAbvGrd  Fireplaces  GarageYrBlt  GarageCars  \
0     -0.219237      0.911897   -0.950901     1.017250    0.319621   
1     -0.219237     -0.318574    0.600289    -0.107890    0.319621   
2     -0.219237     -0.318574    0.600289     0.933906    0.319621   
3     -0.219237      0.296662    0.600289     0.808890    1.672219   
4     -0.219237      1.527133    0.600289     0.892234    1.672219   

   WoodDeckSF  OpenPorchSF  EnclosedPorch  ScreenPorch  PoolArea  SalePrice  \
0   -0.751918     0.216429      -0.359202    -0.270116 -0.069385   0.347154   
1    1.625638    -0.704242      -0.359202    -0.270116 -0.069385   0.007286   
2   -0.751918    -0.070337      -0.359202    -0.270116 -0.069385   0.535970   
3   -0.751918    -0.175988       4.091122    -0.270116 -0.069385  -0.515105   
4    0.779930     0.563567      -0.359202    -0.270116 -0.069385   0.869545   

   MSZoning_C (all)  MSZoning_FV  MSZoning_RH  MSZoning_RL  MSZoning_RM  \
0         -0.083017    -0.215785    -0.105227     0.517956    -0.418812   
1         -0.083017    -0.215785    -0.105227     0.517956    -0.418812   
2         -0.083017    -0.215785    -0.105227     0.517956    -0.418812   
3         -0.083017    -0.215785    -0.105227     0.517956    -0.418812   
4         -0.083017    -0.215785    -0.105227     0.517956    -0.418812   

   Street_Grvl  Street_Pave  LotShape_IR1  LotShape_IR2  LotShape_IR3  \
0    -0.064216     0.064216     -0.703962     -0.169923     -0.083017   
1    -0.064216     0.064216     -0.703962     -0.169923     -0.083017   
2    -0.064216     0.064216      1.419559     -0.169923     -0.083017   
3    -0.064216     0.064216      1.419559     -0.169923     -0.083017   
4    -0.064216     0.064216      1.419559     -0.169923     -0.083017   

   LotShape_Reg  LandContour_Bnk  LandContour_HLS  LandContour_Low  \
0      0.760251        -0.212287        -0.188246        -0.158945   
1      0.760251        -0.212287        -0.188246        -0.158945   
2     -1.314453        -0.212287        -0.188246        -0.158945   
3     -1.314453        -0.212287        -0.188246        -0.158945   
4     -1.314453        -0.212287        -0.188246        -0.158945   

   LandContour_Lvl  LotConfig_Corner  LotConfig_CulDSac  LotConfig_FR2  \
0          0.33701         -0.468578          -0.262234      -0.182318   
1          0.33701         -0.468578          -0.262234       5.481171   
2          0.33701         -0.468578          -0.262234      -0.182318   
3          0.33701          2.132654          -0.262234      -0.182318   
4          0.33701         -0.468578          -0.262234

In [5]:
Bag_kNN = Pipeline([
    ('prep', Prep), 
    ('bag', BaggingRegressor(KNeighborsRegressor(n_neighbors=7, weights='distance'), n_estimators=100))
])

RandFor = Pipeline([
    ('prep', Prep), 
    ('bag', RandomForestRegressor(n_estimators=100))
])

ExTree = Pipeline([
    ('prep', Prep), 
    ('bag', ExtraTreesRegressor(n_estimators=100))
])

AdaB = Pipeline([
    ('prep', Prep), 
    ('bag', AdaBoostRegressor(n_estimators=100))
])

GradB = Pipeline([
    ('prep', Prep), 
    ('bag', GradientBoostingRegressor(n_estimators=100))
])

Models = [
    ("Bag kNN", Bag_kNN),
    ('RandFor', RandFor), 
    ('ExTrees', ExTree), 
    ('AdaB', AdaB),
    ('GradB', GradB)
]

In [6]:
for name, model in Models:
    print name
    print '\t', cross_val_score(model, df.drop("SalePrice", axis=1), df.SalePrice, cv=3, scoring=make_scorer(mean_squared_log_error))

Bag kNN
	

/Users/brendangarrett/anaconda/lib/python2.7/site-packages/pandas/core/generic.py:3295: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)


[ 0.03808122  0.04500383  0.03517586]
RandFor
	[ 0.01953026  0.02404002  0.02135008]
ExTrees
	[ 0.01875796  0.02671833  0.02055463]
AdaB
	[ 0.03715334  0.04338534  0.04048926]
GradB
	[ 0.01447778  0.02151079  0.01800248]


#### Random Forest, ExtraTrees, and GradientBoosting seem to be the best models with default hyperparams
 Do GridSearchCV to find better hyperparams

In [7]:
param_grid = [
    {'bag__n_estimators' : [1,10, 50, 100, 500, 1000]}
]

grid_search = GridSearchCV(ExTree, param_grid, cv=3, scoring=make_scorer(mean_squared_log_error))
grid_search.fit(df.drop(["SalePrice"], axis=1), df.SalePrice)
zip(grid_search.cv_results_["mean_test_score"],grid_search.cv_results_["params"])

[(0.047740336191483171, {'bag__n_estimators': 1}),
 (0.02393405988683844, {'bag__n_estimators': 10}),
 (0.022121865637518653, {'bag__n_estimators': 50}),
 (0.021762093803667878, {'bag__n_estimators': 100}),
 (0.021780278826132968, {'bag__n_estimators': 500}),
 (0.02145741822352824, {'bag__n_estimators': 1000})]

In [8]:
param_grid = [
    {'bag__n_estimators' : [1,10, 50, 100, 500, 1000]}
]

grid_search2 = GridSearchCV(GradB, param_grid, cv=3, scoring=make_scorer(mean_squared_log_error))
grid_search2.fit(df.drop(["SalePrice"], axis=1), df.SalePrice)
zip(grid_search2.cv_results_["mean_test_score"],grid_search.cv_results_["params"])

[(0.14494506715327282, {'bag__n_estimators': 1}),
 (0.059736048957318495, {'bag__n_estimators': 10}),
 (0.02087601225108222, {'bag__n_estimators': 50}),
 (0.018061917534497974, {'bag__n_estimators': 100}),
 (0.01706036620161459, {'bag__n_estimators': 500}),
 (0.016899411824606601, {'bag__n_estimators': 1000})]

In [9]:
param_grid = [
    {'bag__n_estimators' : [1,10, 50, 100, 500, 1000]}
]

grid_search3 = GridSearchCV(RandFor, param_grid, cv=3, scoring=make_scorer(mean_squared_log_error))
grid_search3.fit(df.drop(["SalePrice"], axis=1), df.SalePrice)
zip(grid_search3.cv_results_["mean_test_score"],grid_search3.cv_results_["params"])

[(0.048641785569200797, {'bag__n_estimators': 1}),
 (0.024085429180628622, {'bag__n_estimators': 10}),
 (0.022067027734508384, {'bag__n_estimators': 50}),
 (0.021851462136995282, {'bag__n_estimators': 100}),
 (0.021256549050969589, {'bag__n_estimators': 500}),
 (0.021329105582525914, {'bag__n_estimators': 1000})]

## GradientBoostingRegressor with 1000 estimators seems to work the best so far

In [10]:
param_grid = [
    {'bag__n_estimators' : [500, 800, 1000]},
    {'bag__loss' : ['ls', 'lad', 'huber']},
    {'bag__learning_rate' : [0.01, 0.05, 0.1, 0.2]},
    {'bag__max_depth' : [2,3,5,7]},
    {'bag__subsample' : [0.7, 1.0]},
    {'bag__max_features' : [None, 'sqrt']}
]

grid_search2 = GridSearchCV(GradB, param_grid, cv=3, scoring=make_scorer(mean_squared_log_error))
grid_search2.fit(df.drop(["SalePrice"], axis=1), df.SalePrice)
zip(grid_search2.cv_results_["mean_test_score"],grid_search2.cv_results_["params"])

[(0.017290105055515374, {'bag__n_estimators': 500}),
 (0.016732352766438981, {'bag__n_estimators': 800}),
 (0.016867120767244677, {'bag__n_estimators': 1000}),
 (0.018055217259151806, {'bag__loss': 'ls'}),
 (0.019296993254005759, {'bag__loss': 'lad'}),
 (0.01799374553998026, {'bag__loss': 'huber'}),
 (0.061302260409518326, {'bag__learning_rate': 0.01}),
 (0.020656818851647798, {'bag__learning_rate': 0.05}),
 (0.018175624146071028, {'bag__learning_rate': 0.1}),
 (0.018535018422424415, {'bag__learning_rate': 0.2}),
 (0.019777090415792814, {'bag__max_depth': 2}),
 (0.017983112170276854, {'bag__max_depth': 3}),
 (0.018373101041465157, {'bag__max_depth': 5}),
 (0.019948600431825978, {'bag__max_depth': 7}),
 (0.017381928386113524, {'bag__subsample': 0.7}),
 (0.017952341434073083, {'bag__subsample': 1.0}),
 (0.018034749758103395, {'bag__max_features': None}),
 (0.019675806264996629, {'bag__max_features': 'sqrt'})]

In [11]:
model = Pipeline([
    ('prep', Prep), 
    ('bag', GradientBoostingRegressor(n_estimators=800, loss='huber', subsample=0.7))
])

r = cross_val_score(model, df.drop("SalePrice", axis=1), df.SalePrice, cv=3, scoring=make_scorer(mean_squared_log_error))
print r, r.mean()

[ 0.01393633  0.02140258  0.0162505 ] 0.0171964703662


# Try it on the test data and make a submission to Kaggle

In [12]:
# Train on entire training dataset 
model.fit(df.drop(['SalePrice'],axis=1), df.SalePrice)

df_test = pd.read_csv("test.csv")
test_predictions = model.predict(df_test)

pd.DataFrame(test_predictions).describe()

0
count    1459.000000
mean   178766.736494
std     77413.739005
min     21586.827926
25%    128701.563174
50%    158293.934190
75%    209288.495966
max    546162.750549

In [13]:
df_test_predictions = pd.DataFrame([df_test.Id.astype(int) , test_predictions]).T
df_test_predictions.columns = ['Id', 'SalePrice']
df_test_predictions['Id'] =df_test_predictions['Id'].astype(int)
df_test_predictions.to_csv("Submission_2.csv", index=False)
df_test_predictions

Id      SalePrice
0     1461  115477.550193
1     1462  161452.414532
2     1463  194524.527108
3     1464  196959.246513
4     1465  179670.196399
5     1466  175468.544157
6     1467  168488.819657
7     1468  170201.114119
8     1469  187439.701625
9     1470  129996.448591
10    1471  192004.533638
11    1472   97866.564663
12    1473   94240.514107
13    1474  155896.537425
14    1475  126983.622271
15    1476  390589.801628
16    1477  253768.322390
17    1478  302286.939611
18    1479  263364.016216
19    1480  476592.160020
20    1481  313719.453264
21    1482  206234.623180
22    1483  172545.091701
23    1484  172910.016587
24    1485  179199.778729
25    1486  196407.873393
26    1487  339422.571021
27    1488  235515.037874
28    1489  208589.855660
29    1490  212704.471118
...    ...            ...
1429  2890   81027.315283
1430  2891  137367.888112
1431  2892   27370.638668
1432  2893   77890.806572
1433  2894   38514.522111
1434  2895  322389.394568
1435  2896  272063.782444
1436  2897  206782.123646
1437  2898  142950.059787
1438  2899  216968.046241
1439  2900  166853.715807
1440  2901  211373.041579
1441  2902  180992.810941
1442  2903  344638.395897
1443  2904  362827.126396
1444  2905   66326.577355
1445  2906  212838.103723
1446  2907  114110.754835
1447  2908  134587.113686
1448  2909  127319.206138
1449  2910   82555.658198
1450  2911   70850.409919
1451  2912  139930.924612
1452  2913   69053.962384
1453  2914   74317.916227
1454  2915   80692.979401
1455  2916   66312.808629
1456  2917  178278.172461
1457  2918  112522.360057
1458  2919  230697.381176

[1459 rows x 2 columns]